FROM alpine:3.21.0
ARG VERSION
LABEL version=$VERSION

ENV TZ Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime
RUN echo ${TZ} > /etc/timezone

# 安装 Postfix 和必要的软件包
RUN apk update && \
    apk add --no-cache ca-certificates && \
    update-ca-certificates

# 安装 Dovecot 和必要的依赖
RUN apk add fish vim net-tools busybox-extras

RUN apk add postfix postfix-mysql
# mailx

# 配置 Postfix
COPY config/main.cf /etc/postfix/main.cf
COPY config/master.cf /etc/postfix/master.cf

# 暴露 SMTP 端口
EXPOSE 25 587

# 启动 Postfix
ENTRYPOINT [ "postfix", "start" ]