FROM alpine:3.21.0
ARG VERSION
LABEL version=$VERSION

ENV TZ Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime
RUN echo ${TZ} > /etc/timezone

# 安装 Postfix 和必要的软件包
RUN apk update && \
    apk add --no-cache ca-certificates && \
    update-ca-certificates

# 安装 Dovecot 和必要的依赖
RUN apk add bind-tools gettext-envsubst mariadb-connector-c
# 调试用的工具
RUN apk add fish vim net-tools busybox-extras

RUN apk add postfix postfix-mysql
# mailx

# 配置 Postfix
COPY config/main.cf /etc/postfix/main.cf
COPY config/master.cf /etc/postfix/master.cf

# SQL  配置
RUN mkdir /etc/postfix/sql
COPY sql/alias.cf.template /etc/postfix/sql/alias.cf.template
COPY sql/domains.cf.template /etc/postfix/sql/domains.cf.template
COPY sql/mailbox.cf.template /etc/postfix/sql/mailbox.cf.template

# 启动文件
WORKDIR /
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 暴露 SMTP 端口
EXPOSE 25 587

# 启动 Postfix
ENTRYPOINT ["sh", "-c", "/entrypoint.sh"]