name: mail

networks:
  vmail-net:

services:
  mysql:
    image: mysql:8.0.40-debian
    restart: on-failure
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - vmail-net
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  dovecot:
    build:
      context: ./dovecot
      dockerfile: dockerfile
    # image: dovecot
    hostname: dovecot
    container_name: dovecot
    ports:
      - 24:24
      - 143:143
      - 993:993
      - 12345:12345
    volumes:
      - ./ssl:/etc/ssl/mail/
      - ./dovecot/sql:/etc/dovecot/sql
    networks:
      - vmail-net
    depends_on:
      - mysql

  opendkim:
    build:
      context: ./opendkim
      dockerfile: dockerfile.alpine
    # image: opendkim
    container_name: opendkim
    hostname: opendkim
    ports:
      - 8891:8891
    networks:
      - vmail-net

  postfix:
    build:
      context: ./postfix
      dockerfile: dockerfile.alpine
    # image: postfix
    container_name: postfix
    # 这里需要设置为域名, postfix 会把主机名给带上
    hostname: viweei.me
    ports:
      - 25:25
      - 587:587
    volumes:
      - ./ssl:/etc/ssl/mail
    networks:
      - vmail-net
    depends_on:
      - dovecot
      - opendkim
