name: mail

networks:
  vmail-net:

services:
  mysql:
    image: mysql:8.0.40-debian
    restart: on-failure
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp:unconfined
    networks:
      - vmail-net
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  dovecot:
    build:
      context: ./dovecot
      dockerfile: dockerfile
    hostname: dovecot
    container_name: dovecot
    ports:
      - 143:143
      - 993:993
    volumes:
      - ./ssl:/etc/ssl/mail/
      - ./dovecot/sql:/etc/dovecot/sql
    networks:
      - vmail-net
    depends_on:
      - mysql

  opendkim:
    build:
      context: ./opendkim
      dockerfile: dockerfile.alpine
    # image: opendkim
    container_name: opendkim
    hostname: opendkim
    environment:
      - DOMAIN=${DOMAIN}
    # 需要把证书弄出来不然一起启动证书就变了
    volumes:
      - ./keys:/etc/opendkim/keys
    networks:
      - vmail-net

  postfix:
    build:
      context: ./postfix
      dockerfile: dockerfile.alpine
    container_name: postfix
    hostname: ${DOMAIN}
    ports:
      - 25:25
      - 587:587
    volumes:
      - ./ssl:/etc/ssl/mail
    networks:
      - vmail-net
    depends_on:
      - dovecot
      - opendkim
