FROM alpine:3.21.0

ENV TZ Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime
RUN echo ${TZ} > /etc/timezone

# 安装 基础软件包
RUN apk update && \
    apk add --no-cache ca-certificates && \
    update-ca-certificates

# 安装 cyrus-sasl
RUN apk add --no-cache cyrus-sasl cyrus-sasl-sql openrc

# 配置 saslauthd 服务
RUN mkdir -p /run/openrc && touch /run/openrc/softlevel \
    && rc-update add saslauthd default

# 复制入口点脚本到容器中
COPY entrypoint.sh /usr/local/bin/

# 确保入口点脚本可执行
RUN chmod +x /usr/local/bin/entrypoint.sh

# 设置入口点脚本
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]