name: all-services

services:
  shadowsocks:
    build:
      context: ./shadowsocks
      dockerfile: dockerfile
      args:
        - PORT=${SS_PORT}
    # image: shadowsocks:latest
    restart: on-failure
    hostname: shadowsocks
    container_name: shadowsocks
    environment:
      - PASSWORD=${PASSWORD}
    networks:
      - shared-net

  frps:
    build:
      context: ./frp
      dockerfile: dockerfile
      args:
        - PORT=${FRP_PORT}
    # image: frps:latest
    restart: on-failure
    hostname: frps
    container_name: frps
    environment:
      - VHOST_PORT=${VHOST_PORT}
      - TOKEN=${PASSWORD}
    networks:
      - shared-net

  nginx:
    image: nginx:stable-alpine3.20
    restart: always
    container_name: nginx
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /var/www:/var/www
    ports:
      - 80:80
      - 443:443
    networks:
      - shared-net

networks:
  shared-net:
    name: shared-net
    external: true
