FROM alpine:3.21.0

ARG DOMAIN
ARG PORT
ARG PASSWORD

ENV TZ Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime
RUN echo ${TZ} > /etc/timezone

# 安装 Postfix 和必要的软件包
RUN apk update && \
    apk add --no-cache ca-certificates wget && \
    update-ca-certificates

# 安装 调试工具
# RUN apk add net-tools procps-ng

WORKDIR /root

# 下载 shadowsocks-rust 和 v2ray-plugin
RUN wget https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.22.0/shadowsocks-v1.22.0.x86_64-unknown-linux-musl.tar.xz
RUN wget https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.2/v2ray-plugin-linux-amd64-v1.3.2.tar.gz

RUN tar -xvf shadowsocks-v1.22.0.x86_64-unknown-linux-musl.tar.xz -C /usr/local/bin  && \
    tar -xvf v2ray-plugin-linux-amd64-v1.3.2.tar.gz -C /usr/local/bin && \
    rm -f *

# 创建配置目录并写入配置文件
RUN mkdir -p /etc/shadowsocks && \
    echo -e '{\n \
      "server": "0.0.0.0",\n \
      "mode": "tcp_and_udp",\n \
      "server_port": '${PORT}',\n \
      "password": "'${PASSWORD}'",\n \
      "timeout": 300,\n \
      "nameserver": "8.8.8.8",\n \
      "fast_open": true,\n \
      "no_delay": true,\n \
      "method": "aes-256-gcm",\n \
      "plugin": "/usr/local/bin/v2ray-plugin_linux_amd64",\n \
      "plugin_opts": "server;path=/stream;mode=websocket;host='${DOMAIN}'"\n \
    }' > /etc/shadowsocks/config.json

RUN echo -e '#!/bin/sh\n \
    cat /etc/shadowsocks/config.json\n \
    /usr/local/bin/ssserver -c /etc/shadowsocks/config.json\n' > /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

EXPOSE ${PORT}

CMD ["/root/entrypoint.sh"]