name: shadowsocks

networks:
  shadowsock-net:

services:
  nginx:
    image: nginx:stable-alpine3.20
    hostname: nginx
    restart: always
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./www/${DOMAIN}:/var/www/${DOMAIN}
    ports:
      - 80:80
      - 443:443
    networks:
      - shadowsock-net

  # shadowsocks:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile
  #     args:
  #       - PORT=${PORT}
  #       - DOMAIN=${DOMAIN}
  #       - PASSWORD=${PASSWORD}
  #   hostname: shadowsocks
  #   container_name: shadowsocks
  #   networks:
  #     - vmail-net
